SELECT
  cleaned.*,
  or_line.* EXCEPT (dim_status, date_opened, id_order)
  ,CASE
     -- Breakfast/Brunch
    WHEN LOWER(dim_category) LIKE '%petit-d%' 
    OR LOWER(dim_category) LIKE '%8h30%' 
    OR LOWER(dim_category) LIKE '%11h30%' 
    OR LOWER(dim_category) LIKE '%petit-déjeuner%'
    OR LOWER(dim_category) LIKE '%petit dej%'
    OR LOWER(dim_category) LIKE '%pdj%' 
    OR LOWER(dim_category) LIKE '%brunch%'
    THEN 'Breakfast' 

    -- Bread
    WHEN LOWER(dim_category) LIKE '%pain%'
    THEN 'Baguette'

    -- Starters: cold/light first courses
    WHEN LOWER(dim_category) LIKE '%entrée%' 
    OR LOWER(dim_category) LIKE '%soupe%' 
    OR LOWER(dim_category) LIKE '%antipasti%' 
    OR LOWER(dim_category) LIKE '%avocado%' 
    OR LOWER(dim_category) LIKE '%salade%' 
    OR LOWER(dim_category) LIKE '%spécialités tibétaines entrée%'
    OR LOWER(dim_category) LIKE '%sides%'
    OR LOWER(dim_category) LIKE '%pour commencer%'
    OR LOWER(dim_category) LIKE '%mix entrée sagarmatha%' 
    OR LOWER(dim_category) LIKE '%in-salades%'
    OR LOWER(dim_category) LIKE '%entées%'
    OR LOWER(dim_category) LIKE '%entrées spécialités tandoor%'
    OR LOWER(dim_category) LIKE '%entrée soupe salades%'
    OR LOWER(dim_category) LIKE '%entrées tandoori%'
    OR LOWER(dim_category) LIKE '%entrées%'
    OR LOWER(dim_category) LIKE '%entrée tibétaines%'
    OR LOWER(dim_category) LIKE '%entrees emp%'
    OR LOWER(dim_category) LIKE '%entrees%'
    OR LOWER(dim_category) LIKE '%avocado toast%'
    THEN 'Starters'

    -- Main courses: substantial meals
    WHEN LOWER(dim_category) LIKE '%plat%' 
    OR LOWER(dim_category) LIKE '%pasta%' 
    OR LOWER(dim_category) LIKE '%wrap%' 
    OR LOWER(dim_category) LIKE '%bowl%' 
    OR LOWER(dim_category) LIKE '%cuisson%' 
    OR LOWER(dim_category) LIKE '%tandoori%' 
    OR LOWER(dim_category) LIKE '%spécialités tibétaines plats%'
    OR LOWER(dim_category) LIKE '%sourie dagneau%'
    OR LOWER(dim_category) LIKE '%soupe et ramen%'
    OR LOWER(dim_category) LIKE '%soupe & bouillon%'
    OR LOWER(dim_category) LIKE '%soupe%'
    OR LOWER(dim_category) LIKE '%royal biryani%'
    OR LOWER(dim_category) LIKE '%riz%'
    OR LOWER(dim_category) LIKE '%repas%'
    OR LOWER(dim_category) LIKE '%poisson%'
    OR LOWER(dim_category) LIKE '%crevettes%'
    OR LOWER(dim_category) LIKE '%gambas%'
    OR LOWER(dim_category) LIKE '%plats vegetarien%'
    OR LOWER(dim_category) LIKE '%plats%'
    OR LOWER(dim_category) LIKE '%poulet%'
    OR LOWER(dim_category) LIKE '%agneau%'
    OR LOWER(dim_category) LIKE '%plat du jour%'
    OR LOWER(dim_category) LIKE '%pizza%'
    OR LOWER(dim_category) LIKE '%pasta%'
    OR LOWER(dim_category) LIKE '%mix grill%' 
    OR LOWER(dim_category) LIKE '%légumes%' 
    OR LOWER(dim_category) LIKE '%cuissons%'
    OR LOWER(dim_category) LIKE '%cuisson%'
    OR LOWER(dim_category) LIKE '%coursemeal%'
    OR LOWER(dim_category) LIKE '%contorni%'
    OR LOWER(dim_category) LIKE '%bocaux repas%'
    OR LOWER(dim_category) LIKE '%biriyani%'
    OR LOWER(dim_category) LIKE '%autres spƒecialites chaudes%'
    OR LOWER(dim_category) LIKE '%autres spƒcialitƒs chaudes%'
    OR LOWER(dim_category) LIKE '%accompagnements%'
    THEN 'Main Course'

    -- Spices, seasoning, dressing
    WHEN LOWER(dim_category) LIKE '%condiments%'
    THEN 'Spices'

    -- Desserts
    WHEN LOWER(dim_category) LIKE '%dessert%' 
    OR LOWER(dim_category) LIKE '%sucr%' 
    OR LOWER(dim_category) LIKE '%sorbets%'
    OR LOWER(dim_category) LIKE '%glace%'
    OR LOWER(dim_category) LIKE '%patisserie%' 
    OR LOWER(dim_category) LIKE '%patisserie%' 
    OR LOWER(dim_category) LIKE '%parfum%' 
    OR LOWER(dim_category) LIKE '%parfums%' 
    OR LOWER(dim_category) LIKE '%glaces%' 
    OR LOWER(dim_category) LIKE '%coulis%' 
    OR LOWER(dim_category) LIKE '%panna cotta%' 
    OR LOWER(dim_category) LIKE '%les sucrés%'
    OR LOWER(dim_category) LIKE '%les sucres%'
    OR LOWER(dim_category) LIKE '%gouts%'
    OR LOWER(dim_category) LIKE '%gout%'
    OR LOWER(dim_category) LIKE '%desserts à emporter%'
    OR LOWER(dim_category) LIKE '%desserts vae%'
    OR LOWER(dim_category) LIKE '%desserts sur place%'
    OR LOWER(dim_category) LIKE '%desserts a e%'
    OR LOWER(dim_category) LIKE '%desserts%'
    OR LOWER(dim_category) LIKE '%dessert maison%'
    OR LOWER(dim_category) LIKE '%confiserie%'
    OR LOWER(dim_category) LIKE '%choix parfum%'
    OR LOWER(dim_category) LIKE '%chocolat plaq%'
    OR LOWER(dim_category) LIKE '%ae en version glacee%'
    THEN 'Dessert'

    -- Drinks
    WHEN LOWER(dim_category) LIKE '%vin%'
    OR LOWER(dim_category) LIKE '%rose bouteille%'
    OR LOWER(dim_category) LIKE '%rouge bouteille%'
    OR LOWER(dim_category) LIKE '%blanc verre%'
    OR LOWER(dim_category) LIKE '%rose verre%'
    OR LOWER(dim_category) LIKE '%rouge verre%'
    OR LOWER(dim_category) LIKE '%blanc bouteille%'
    OR LOWER(dim_category) LIKE '%valpolicella%'
    OR LOWER(dim_category) LIKE '%valle d%'
    OR LOWER(dim_category) LIKE '%touraine gamay%'
    OR LOWER(dim_category) LIKE '%toscane%'
    OR LOWER(dim_category) LIKE '%saumur%'
    OR LOWER(dim_category) LIKE '%médoc%' 
    OR LOWER(dim_category) LIKE '%château%'
    OR LOWER(dim_category) LIKE '%muscadet sur lie%' 
    OR LOWER(dim_category) LIKE '%les vins blancs%' 
    OR LOWER(dim_category) LIKE '%kir%'
    OR LOWER(dim_category) LIKE '%i.g.p. côtes du tarn%'
    OR LOWER(dim_category) LIKE '%grover%'
    OR LOWER(dim_category) LIKE '%delamotte%'
    OR LOWER(dim_category) LIKE '%côtes du rhône%'
    OR LOWER(dim_category) LIKE '%côtes de provence%'
    OR LOWER(dim_category) LIKE '%cave%'
    OR LOWER(dim_category) LIKE '%castel del monte%'
    OR LOWER(dim_category) LIKE '%carte des vins%'
    OR LOWER(dim_category) LIKE '%buzet merlot%'
    OR LOWER(dim_category) LIKE '%brouilly%'
    OR LOWER(dim_category) LIKE '%bourgueil le plessis%'
    OR LOWER(dim_category) LIKE '%bordeaux supérieur goélane%'
    OR LOWER(dim_category) LIKE '%bordeaux rouges a.o.p%'
    OR LOWER(dim_category) LIKE '%bar/vin%'
    OR LOWER(dim_category) LIKE '%anjou chenin%'
    OR LOWER(dim_category) LIKE '%alsace riesling%'
    OR LOWER(dim_category) LIKE '%alsace pinot noir%'
    THEN 'Wine' 

    WHEN LOWER(dim_category) LIKE '%soft%' 
    OR LOWER(dim_category) LIKE '%jus%' 
    OR LOWER(dim_category) LIKE '%boisson%' 
    OR LOWER(dim_category) LIKE '%eaux%'
    OR LOWER(dim_category) LIKE '%charitea-mate%'
    OR LOWER(dim_category) LIKE '%cidre appie%'
    OR LOWER(dim_category) LIKE '%soda%'
    OR LOWER(dim_category) LIKE '%jus de fruits%'
    OR LOWER(dim_category) LIKE '%sirop%'
    OR LOWER(dim_category) LIKE '%san pellegrino%'
    OR LOWER(dim_category) LIKE '%boissons froides%'
    OR LOWER(dim_category) LIKE '%petillants%' 
    OR LOWER(dim_category) LIKE '%petillant%' 
    OR LOWER(dim_category) LIKE '%minerales%' 
    OR LOWER(dim_category) LIKE '%les eaux%'
    OR LOWER(dim_category) LIKE '%laurent-perrier%'
    OR LOWER(dim_category) LIKE '%lassi%'
    OR LOWER(dim_category) LIKE '%nectar%'
    OR LOWER(dim_category) LIKE '%jus de fruit%'
    OR LOWER(dim_category) LIKE '%jus de fruits%'
    OR LOWER(dim_category) LIKE '%evian%'
    OR LOWER(dim_category) LIKE '%eau minerale%'
    OR LOWER(dim_category) LIKE '%drinks%'
    OR LOWER(dim_category) LIKE '%charitea-mate%'
    OR LOWER(dim_category) LIKE '%boissons%'
    OR LOWER(dim_category) LIKE '%boissons vae%'
    OR LOWER(dim_category) LIKE '%boissons sans alcool%'
    OR LOWER(dim_category) LIKE '%boissons resto%'
    OR LOWER(dim_category) LIKE '%boissons indiennes%'
    OR LOWER(dim_category) LIKE '%boissons gazeuses%'
    OR LOWER(dim_category) LIKE '%boissons fraîches%'
    OR LOWER(dim_category) LIKE '%boissons fraiches%'
    OR LOWER(dim_category) LIKE '%bar / boissons froides%'
    OR LOWER(dim_category) LIKE '%ae boissons fraiches%'
    THEN 'Soft Drinks'

    WHEN LOWER(dim_category) LIKE '%bière%'
    OR LOWER(dim_category) LIKE '%bières%'
    OR LOWER(dim_category) LIKE '%biere%'
    OR LOWER(dim_category) LIKE '%bieres%'
    OR LOWER(dim_category) LIKE '%bière epicerie%' 
    OR LOWER(dim_category) LIKE '%bieres bouteilles%'
    OR LOWER(dim_category) LIKE '%biere bio%'
    OR LOWER(dim_category) LIKE '%beers%'
    OR LOWER(dim_category) LIKE '%bar / bieres%'
    THEN 'Bottled Beer'
    
    WHEN LOWER(dim_category) LIKE '%cidres/bières%'
    OR LOWER(dim_category) LIKE '%cidres%'
    OR LOWER(dim_category) LIKE '%cidre appie%'
    OR LOWER(dim_category) LIKE '%cidres bouteilles%'
    THEN 'Cider'

    WHEN LOWER(dim_category) LIKE '%pression%'
    OR LOWER(dim_category) LIKE '%bieres pressions%'
    OR LOWER(dim_category) LIKE '%bieres pression%'
    THEN 'Draft beer'

    WHEN LOWER(dim_category) LIKE "%alcool%"
    OR LOWER(dim_category) LIKE '%rooibos glace bos%'
    OR LOWER(dim_category) LIKE '%roibos glace bos%'
    OR LOWER(dim_category) LIKE '%roiboos glace bos%'
    OR LOWER(dim_category) LIKE '%cless%'
    OR LOWER(dim_category) LIKE '%sfizio%'
    OR LOWER(dim_category) LIKE '%cocktails%'
    OR LOWER(dim_category) LIKE '%cocktail%' 
    OR LOWER(dim_category) LIKE '%martini 15 cl%'
    OR LOWER(dim_category) LIKE '%martini%'
    OR LOWER(dim_category) LIKE '%long drink%'
    OR LOWER(dim_category) LIKE '%les alcools%'
    OR LOWER(dim_category) LIKE '%ice ice baby%'
    OR LOWER(dim_category) LIKE '%happy hour%'
    OR LOWER(dim_category) LIKE '%boisson alcoolisées%'
    OR LOWER(dim_category) LIKE '%boisson alcoolisée%'
    OR LOWER(dim_category) LIKE '%amis du buddha%'
    THEN 'Cocktails'
    
    WHEN LOWER(dim_category) LIKE '%whiskys%'
    OR LOWER(dim_category) LIKE '%digestifs 2 cl%'
    OR LOWER(dim_category) LIKE '%digestifs%'
    OR LOWER(dim_category) LIKE '%bar / aperitif%'
    OR LOWER(dim_category) LIKE '%aperitifs & spiritueux%'
    OR LOWER(dim_category) LIKE '%antipasti%'
    OR LOWER(dim_category) LIKE '%alcools forts%'
    OR LOWER(dim_category) LIKE '%alcools (4cl)%'
    OR LOWER(dim_category) LIKE '%alcools sup%'
    OR LOWER(dim_category) LIKE '%alcools salle%'
    OR LOWER(dim_category) LIKE '%alcool%'
    THEN 'Spirits'
    
    WHEN LOWER(dim_category) LIKE '%champagne%'
    THEN 'Champagne'

    WHEN LOWER(dim_category) LIKE '%cafe%'
    OR LOWER(dim_category) LIKE '%the%'
    OR LOWER(dim_category) LIKE '%chocolat%'
    OR LOWER(dim_category) LIKE '%thé%'
    OR LOWER(dim_category) LIKE '%boissons chaudes%'
    OR LOWER(dim_category) LIKE '%mug%' 
    OR LOWER(dim_category) LIKE '%instantané%'
    OR LOWER(dim_category) LIKE '%filtres%'
    OR LOWER(dim_category) LIKE '%expression expresso%'
    OR LOWER(dim_category) LIKE '%cafés en grain%'
    OR LOWER(dim_category) LIKE '%cafés%'
    OR LOWER(dim_category) LIKE '%cafetières%'
    OR LOWER(dim_category) LIKE '%cafeterie%'
    OR LOWER(dim_category) LIKE '%bouilloire%'
    OR LOWER(dim_category) LIKE '%boissons chaudes%'
    OR LOWER(dim_category) LIKE '%bar / boissons chaudes%'
    OR LOWER(dim_category) LIKE '%autres spécialités tasse%'
    OR LOWER(dim_category) LIKE '%ae moccamaster drip%'
    OR LOWER(dim_category) LIKE '%ae espressions%'
    OR LOWER(dim_category) LIKE '%ae boissons chaudes%'
    THEN 'Hot drinks'

    -- Fromage
    WHEN LOWER(dim_category) LIKE '%fromages%%'
    OR LOWER(dim_category) LIKE '%frawmages%'
    THEN 'Cheese'

    -- Combo or menu bundles
    WHEN LOWER(dim_category) LIKE '%formule%' 
    OR LOWER(dim_category) LIKE '%choix%' 
    OR LOWER(dim_category) LIKE '%menus à emporter%'
    OR LOWER(dim_category) LIKE '%petillant%'
    OR LOWER(dim_category) LIKE '%menus%'
    OR LOWER(dim_category) LIKE '%menu soir%'
    OR LOWER(dim_category) LIKE '%menu saint sylvestre%'
    OR LOWER(dim_category) LIKE '%menu midi%'
    OR LOWER(dim_category) LIKE '%menu express%'
    OR LOWER(dim_category) LIKE '%menu enfant%'
    OR LOWER(dim_category) LIKE '%menu dégustation%'
    OR LOWER(dim_category) LIKE '%menu découverte%'
    OR LOWER(dim_category) LIKE '%menu 25,00%'
    OR LOWER(dim_category) LIKE '%menu 16,50%'
    OR LOWER(dim_category) LIKE '%menu%'
    OR LOWER(dim_category) LIKE '%formules du jour%'
    OR LOWER(dim_category) LIKE '%formules%'
    OR LOWER(dim_category) LIKE '%formule plat dessert%'
    OR LOWER(dim_category) LIKE '%formule livraison%'
    OR LOWER(dim_category) LIKE '%formule entrée plat%' 
    OR LOWER(dim_category) LIKE '%formule déjeuner%'
    OR LOWER(dim_category) LIKE '%formule dejeuner%'
    OR LOWER(dim_category) LIKE '%entrees formule%'
    OR LOWER(dim_category) LIKE '%dîner%'
    OR LOWER(dim_category) LIKE '%déjeuner%'
    OR LOWER(dim_category) LIKE '%dinner menu%'
    OR LOWER(dim_category) LIKE '%choix vegetarien sud%'
    OR LOWER(dim_category) LIKE '%choix vegetarien nord%'
    OR LOWER(dim_category) LIKE '%choix de la formule%'
    OR LOWER(dim_category) LIKE '%carte midi%'
    OR LOWER(dim_category) LIKE '%carte du soir%'
    OR LOWER(dim_category) LIKE '%carte du midi%'
    THEN 'Menu'
   
    -- Snacks
    WHEN LOWER(dim_category) LIKE '%planche%'
    OR LOWER(dim_category) LIKE '%tapas%'
    OR LOWER(dim_category) LIKE '%snacks%'
    OR LOWER(dim_category) LIKE '%sandwich%'
    OR LOWER(dim_category) LIKE '%aperitifs%'
    OR LOWER(dim_category) LIKE '%grignotages%'
    OR LOWER(dim_category) LIKE '%focaccia%'
    OR LOWER(dim_category) LIKE '%envies salfes%'
    OR LOWER(dim_category) LIKE '%envies salées%'
    OR LOWER(dim_category) LIKE '%charcuterie%'
    OR LOWER(dim_category) LIKE '%breizh%'
    OR LOWER(dim_category) LIKE '%apéro%'
    OR LOWER(dim_category) LIKE '%apéritifs%'
    OR LOWER(dim_category) LIKE '%aperitivo%'
    OR LOWER(dim_category) LIKE '%aperitifs%'
    OR LOWER(dim_category) LIKE '%alcools et apéros%'
    THEN 'Snacks'

    -- Shisha
    WHEN LOWER(dim_category) LIKE '%chicha%'
    THEN 'Shisha'

    -- Events
    WHEN LOWER(dim_category) LIKE '%bal bastille%'
    OR LOWER(dim_category) LIKE '%soiree priv%'
    OR LOWER(dim_category) LIKE '%privat%'
    OR LOWER(dim_category) LIKE '%spectacle%'
    OR LOWER(dim_category) LIKE '%saint valentin%'
    OR LOWER(dim_category) LIKE '%réveillon%'
    OR LOWER(dim_category) LIKE '%reveillon%'
    OR LOWER(dim_category) LIKE '%easter%'
    OR LOWER(dim_category) LIKE '%džgustation de 3 crus%'
    OR LOWER(dim_category) LIKE '%dégustation de 3 crus%'
    OR LOWER(dim_category) LIKE '%dégustation / visite%'
    OR LOWER(dim_category) LIKE '%droit de bouchon%'
    OR LOWER(dim_category) LIKE '%drinks lunch%'
    OR LOWER(dim_category) LIKE '%bal bastille%'
    THEN 'Events'

    -- Refunds
    WHEN LOWER(dim_category) LIKE '%consigne%'
    OR LOWER(dim_category) LIKE '%avoir%'
    THEN 'Pfand'

    -- Everything else
    ELSE 'Other'
  END AS refined_category

FROM `tiller-by-sumup-461710.Tiller.order_data_Kcleaned` AS cleaned
JOIN `tiller-by-sumup-461710.Tiller.order_line` AS or_line
USING(id_order);